.github/workflows/semantic.yml, .gitignore, .releaserc.json, CHANGELOG.md, build.gradle, package-lock.json, package.json
시맨틱 릴리즈 적용했습니다.
1. npm으로 시맨틱 릴리즈 설정했습니다
2. 디비 연결이 안되어서 훅 설정에 오류가 발생하여 build.gradle에 jpa 관련 설정 주석처리 했습니다. 추후 디비 연결 후에 다시 주석 풀면 될 것 같습니다.
=> feat: 시맨틱 릴리즈 설정 추가

.gitignore, build.gradle, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/controller/DashboardController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/controller/request/RequestCoinMarket.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/controller/request/RequestKimchiPremium.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/controller/response/CoinDTO.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/controller/response/ResponseCoinMarket.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/controller/response/ResponseKimchiPremium.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/CoinMarketRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/CoinMarketRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/KimchiPreminumRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/KimchiPremiumRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/entity/CoinMarketEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/entity/KimchiPremiumEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/jpa/CoinMarketJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/repository/jpa/KimchiPreminumJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/service/CoinMarketService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/service/CoinMarketServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/service/KimchiPremiumService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/dashboard/service/KimchiPremiumServiceImpl.java
dashboard 도메인 셋팅
1. dashboard 개발전 파일 셋팅
=> feat: dashboard 도메인 셋팅

build.gradle, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/swagger/SwaggerAlertController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/controller/swagger/SwaggerDashboardController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/swagger/SwaggerUserController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/SwaggerConfig.java, src/main/resources/application.yml
Swagger API 문서화를 위해 Swagger 설정을 추가하고, API 엔드포인트를 관리하는 컨트롤러를 생성했습니다.
이를 통해 개발자들이 Swagger UI에서 API 명세를 쉽게 확인할 수 있습니다.
1. SwaggerConfig.java 추가
- Swagger API 문서 자동 생성을 위한 설정 적용
- /swagger-ui.html 경로에서 Swagger UI 접근 가능
- Swagger 관련 컨트롤러 추가
2. SwaggerAlertController.java → 알람 관련 API 명세 추가
- SwaggerDashboardController.java → 대시보드 관련 API 명세 추가
- SwaggerUserController.java → 사용자 관련 API 명세 추가
3. application.yml 업데이트
- springdoc.swagger-ui.enabled=true 설정 추가
http://localhost:8080/swagger-ui/index.html 접속
=> docs: 전체 API Swagger 문서 업데이트

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/TickerTestRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/QueryDslConfig.java
- 기존 jpql 코드 QueryDsl로 리팩토링
1.  QueryDsl 설정
2. 기존 jpql 코드를 QueryDsl로 리팩토링
=> feat: QueryDsl 설정

src/main/java/_1danhebojo/coalarm/coalarm_service/CoalarmServiceApplication.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/KimchiPremiumRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/KimchiPremiumRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/TickerTestRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/TickerTestRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/jpa/CoinJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/KimchiPremiumScheduler.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/KimchiPremiumServiceImpl.java
스케쥴러를 통해 5분에 한번씩 ticker 데이터를 가져와서 계산후 DB에 데이터를 저장하는 로직을 추가하였음(초안이기에 추후에 변동 발생할 수 있음)
=> feat: 김치 프리미엄 계산후 DB저장

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/controller/DashboardController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/controller/request/RequestCoinMarket.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/controller/response/CoinIndicatorResponse.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/controller/response/ResponseCoinMarket.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/CoinIndicatorRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/CoinIndicatorRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/entity/CoinIndicatorEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/jpa/CoinMarketJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinIndicatorService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinIndicatorServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinMarketService.java
- CoinMarket → CoinIndicator로 명칭 변경
- 서비스 및 레포지토리 관련 클래스, 인터페이스, 메서드, 변수명 변경
- 관련 파일 및 패키지명 수정 반영
1.CoinMarket 네이밍을 전부 CoinIndicator로 변경하였습니다
=> refactor: CoinMarket → CoinIndicator로 명칭 변경

build.gradle, src/main/java/_1danhebojo/coalarm/coalarm_service/CoalarmServiceApplication.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/OAuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/response/UserDTO.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/entity/UserEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/UserRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/UserRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/jpa/UserJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/KakaoAuthService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/KakaoAuthServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/util/NicknameGenerator.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/JwtProperties.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/KakaoProperties.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/JwtTokenProvider.java
카카오 OAuth 기반 로그인 기능을 추가
JWT 인증을 적용
카카오 로그인 후 JWT 토큰을 발급하고, 이를 응답에 포함
1. 카카오 OAuth 기본 구조 추가
2. 유저 서비스 및 회원가입 기능 추가
3. 랜덤 닉네임 생성 기능 추가
4. Spring Security 및 JWT 라이브러리 추가
5. JWT Token Provider 및 설정 추가
6. 카카오 로그인 후 JWT 토큰 발급 로직 추가
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
향후 JWT 인증을 API 보안에 적용하는 작업 필요
=> 카카오 OAuth 기반 로그인 기능 추가

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/OAuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/UserController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/response/UserDTO.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/UserRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/UserRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/entity/UserEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/jpa/UserJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/KakaoAuthServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/JwtAuthenticationFilter.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/JwtTokenProvider.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
JWT 기반 인증 및 카카오 OAuth 로그인 적용
Closes #21
- JWT 토큰 발급 및 검증 기능 추가 (JwtTokenProvider)
- JWT 기반 사용자 인증 API 추가 (UserController, /user/me)
- OAuthController에서 로그인 후 JWT 토큰 발급
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> JWT 기반 인증 및 카카오 OAuth 로그인 적용

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/AuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/OAuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/UserController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/response/TokenResponse.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/response/UserLoginResponse.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/entity/RefreshTokenEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/jpa/RefreshTokenJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/KakaoAuthServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/RefreshTokenService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/RefreshTokenServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/api/AppHttpStatus.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/JwtAuthenticationFilter.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
OAuth 로그인 및 인증 개선, Refresh Token 및 로그아웃 기능 추가, 보안 설정 정리
1. AuthController 추가 및 Refresh Token 기능 구현
2. OAuth 로그인 및 인증 기능 개선
- 기존 OAuthController의 응답을 UserLoginResponse DTO로 변경
- 로그인 시 Refresh Token도 함께 발급
3. Refresh Token 및 로그아웃 기능 추가
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Refresh Token 기반 인증 기능 추가

build.gradle, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/KimchiPremiumScheduler.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/UserController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/request/UserUpdateRequest.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/entity/UserEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/S3Service.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/api/AppHttpStatus.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/S3Config.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
- S3 연동 로직 추가
- 회원의 이미지 및 닉네임 수정 기능 추가
Api 추가
- Resolves #[37]
1. S3 연결 설정 파일 추가(S3Config)
2. 회원정보 수정 엔드포인트 추가
3. S3 조작 서비스 추가 (S3Service)
=> feat: 회원정보 수정 추가

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertService.java
디스코드 웹훅의 유효성 검사 기능을 추가하고, 알람 수정 시 SSE에서 해당 알람을 올바르게 제거하는 기능을 구현
- Resolves #51 
1. 디스코드 웹훅의 유효성 검사 기능 추가
2. 알람 수정 시 SSE에서 해당 알람을 올바르게 제거하도록 처리
- 유효하지 않은 디스코드 웹훅 입력 시 차단되는지 확인
- SSE에서 알람 수정 시 제거되는지 확인
=> feat: 디스코드 웹훅 유효성 검사 추가 및 알람 수정 시 SSE 알람 제거 처리

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertService.java
알림 추가 시 SSE에 반영되지 않는 버그를 수정하였습니다.
1. SSE 이벤트가 정상적으로 전송되지 않는 문제 수정
- AlertService에서 알림 생성 시 SseEmitter로 이벤트가 즉시 전송되도록 로직 수정
- SSE 연결 유효성 체크 로직 추가
2. SSE 연결이 끊어졌을 경우 새로운 Emitter를 할당하도록 수정
1. 알림 생성 시 SSE 전송 확인
- 특정 사용자의 알림을 생성한 후, SSE 이벤트가 정상적으로 전달되는지 확인
=> fix: 알림 추가 시 SSE에 반영되지 않는 버그 수정

.github/workflows/deploy.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> feat: health check controller 테스트 2

.github/workflows/deploy.yml, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/health/controller/HealthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> 개발 환경 eb 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/AlertJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java
기존에 알람기능이 구현이 되지 하지 않아 회원삭제로직에 알람 삭제로직이 없었음
알람기능 구현으로 인하여 사용자의 알람 또한 삭제되게 추가하였음
=> feat: 회원탈퇴시 유저의 알람 삭제

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/AlertController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/health/controller/HealthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/AuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/OAuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/UserController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
컨트롤러 단 엔드포인트에 /api/v1 추가
1. 컨트롤러 단 엔드포인트에 /api/v1 추가
=> feat: 엔드포인트 api/v1 분기처리

.github/workflows/deploy.yml
swagger 테스트
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: swagger 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: security config 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/controller/DashboardController.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: 대시보드 컨트롤러 엔드포인트 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/OAuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/WebConfig.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
cors 설정 추가 및 로그인 url api 작성했습니다.
1. cors 설정
2. 로그인 Url api 작성
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> feat: cors 설정 추가 및 로그인 url API 작성

src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/JwtAuthenticationFilter.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
SecurityConfig 에서 접근 가능 요청 범위 수정
1. SecurityConfig 요청 범위 수정
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> feat: 인증 없이 접근 가능한 요청 범위 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/WebConfig.java
WebConfig 파일 수정하여 https localhost cors 방지
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: WebConfig 파일 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/UserController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java
유저와 관련된 엔드포인트에 대해서UserDetails 대신 현재 로그인중인 유저 ID를 받도록 변경
1. UserController 에서 로그인한 유저 정보를 UserDetails에서 유저 ID로 받을 수 있도록 변경
2. [변경 내용 2]
3. [변경 내용 3]
1. Postman을 통해서 테스트 완료
2. [테스트 2]
3. [테스트 3]
=> fix : 유저와 관련된 엔드포인트에 대해서UserDetails 대신 현재 로그인중인 유저 ID를 받도록 변경

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/controller/CoinController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/jpa/CoinJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinServiceImpl.java
대시보드에서 코인 검색하는 api 구현했습니다
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> feat: 코인 검색 api 구현

.github/workflows/deploy.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> docs: deploy.yml 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/global/security/SecurityConfig.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: security config 테스트 임시 허용

src/main/java/_1danhebojo/coalarm/coalarm_service/global/jwt/JwtVerificationFilter.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: 401 에러 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/global/jwt/JwtVerificationFilter.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: 401 에러 수정(테스트)

.github/workflows/deploy.yml, src/main/java/_1danhebojo/coalarm/coalarm_service/CoalarmServiceApplication.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: oAuth 2.0 리다이렉트 에러 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/AlertController.java
알람 기능에 사용자 정보를 명확히 매핑하기 위해 getAlertList와 addAlert 로직에 userId를 적용
- addAlert 메서드에서 인증된 사용자로부터 userId를 추출해 알람 저장 시 포함
- getAlertList 메서드에서 로그인된 사용자 기준으로 알람 리스트 조회하도록 수정
1. 로그인된 사용자로 알람 추가 시 userId가 정상적으로 저장되는지 확인
2. getAlertList 호출 시 해당 사용자의 알람만 필터링되어 조회되는지 확인
=> refactor: getAlertList와 addAlert 메서드에 userId를 활용

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/entity/CoinIndicatorEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinIndicatorServiceImpl.java
롱숏 비율 계산 방식 longStrength 기반으로 변경하였습니다
1. 롱숏 비율 계산 방식 longStrength 기반으로 변경
2. longRatio, shortRatio를 항상 0~100 사이의 값으로 반환하게 변경
=> feat: 롱숏 비율 계산 방식 longStrength 기반으로 변경

.github/workflows/deploy.yml, k8s/deployment.yaml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> feat: 쿠버네티스 cicd 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/AlertController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/entity/CoinIndicatorEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinIndicatorServiceImpl.java
사용자가 설정한 알람 목록 조회 기능을 수정
1. 사용자가 설정한 알람의 목록을 조회하는 엔드포인트를 수정했습니다.
2. [변경 내용 2]
3. [변경 내용 3]
1. 포스트맨으로 테스트를 완료했습니다.
2. 로컬에서 프론트 API 연동 테스트르 완료했습니다.
3. [테스트 3]
=>  사용자가 설정한 알람 목록 조회 기능을 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinIndicatorServiceImpl.java
- 알람 서비스 심볼 조회 수정
- 코인 지표 불필요한 코드 삭제 및 수정
=> fix: 병합중 발생한 오류 수정

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> docs: 개발환경 deploy.yml 명칭 수정-2

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/AuthController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/AuthService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/AuthServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/oauth/OAuthFailureHandler.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/oauth/OAuthSuccessHandler.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/properties/KakaoProperties.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/properties/OAuthProperties.java
OAuth 로그아웃 구현
1. 로그아웃 엔드포인트 구현
2. OAuthProperties 수정
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> OAuth 로그아웃 구현

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/controller/UserController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/UserRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/repository/UserRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/AuthServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/api/AppCookie.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/oauth/OAuthSuccessHandler.java
Feat : 회원 탈퇴 기능을 구현
1. 카카오 액세스 토큰을 통해 카카오 유저 언링크 API 호출
2. 쿠키 사용할 때 중복되는 코드를 제거
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Feat : 회원 탈퇴 기능을 구현

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java
- SSE 연결 유지를 위한 heartbeat 이벤트 주기적 전송 추가
- 중간중간 전체 알람 상태 재로딩
- SSE 전송 큐를 통해 3초 마다 전송
=> feat: SSE 연결 관련 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/CoalarmServiceApplication.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/properties/AlarmProperties.java
- 알람 메세지 전송 큐로 관리
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> refactor: 알람 메세지 전송 큐로 관리

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: eb 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/TickerRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/entity/TickerCompositeKey.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/entity/TickerEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/jpa/TickerJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/KimchiPremiumServiceImpl.java
- Ticker테이블 변경으로 으로인한 관련 entity 변경완료
- TickerEntity 변경으로 인한 사용하는 서비스중 김치프리미엄 변경 완료
=> fix: TickerEntity 구조 변경 & 변경에 따른 김치프리미엄 변경

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/controller/CoinController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/controller/response/CoinWithPriceDTO.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/service/CoinService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/service/CoinServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/TickerRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/TickerRepositoryImpl.java
/search 엔드포인트에서 반환하던 CoinDTO 대신, 각 코인의 최신 가격 정보를 포함한 CoinWithPriceDTO로 응답 수정
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> CoinWithPriceDTO 추가

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/controller/response/CoinWithPriceDTO.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/service/CoinServiceImpl.java
CoinWithPriceDTO에 TickerEntity의 timestamp 추가했습니다
1. CoinWithPriceDTO에 OffsetDateTime timestamp 필드 추가
1. [테스트 1]
3. [테스트 2]
4. [테스트 3]
=> feat: CoinWithPriceDTO에 TickerEntity의 timestamp 추가

build.gradle, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/AlertController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/UpbitSseController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/UpbitSseService.java
프론트엔드에서 웹 소켓을 사용하여 업비트 429에러 발생하던 부분 프록시 서버를 사용하여 개선
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: 실시간 거래체결 웹 소켓 연결

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java
존재하는 emitter 정보 있으면 재사용 하도록 수정
_
=> refactor: SSE 재사용 처리

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java
SSE 중복 연결 제거 및 emitter 초기화 로직 추가하여 테스트 예정
1. SSE 중복 연결 제거 및 emitter 초기화 로직 추가
=> test: SSE 중복 연결 제거 및 emitter 초기화 로직 추가

.github/workflows/deploy-prd-kube.yml, k8s/deployment.yaml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: deployment.yaml 메모리 설정 추가

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: Hikari 설정 추가

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/UpbitSseController.java
produces = MediaType.TEXT_EVENT_STREAM_VALUE 명시적으로 설정하여 응답 포맷 명확화
=> refactor: Upbit SSE subscribe API에 produces 명시 및 예외 처리 추가

.github/workflows/deploy-dev-eb.yml
=> fix: Hikari 설정 변경

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/AsyncConfig.java
- AlertSSEService 주요 알림 전송 메서드에 @Async 적용
- SseEmitter 전송 실패 시 안전한 제거 로직 추가로 안정성 강화
-
=> refactor: SSE 알림 로직 비동기 처리로 성능 개선

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/api/AppHttpStatus.java
백엔드에 디스코드 웹훅 url 유효성 검사 로직을 추가하였습니다.
1. UserServiceImpl에 validateDiscordWebhookUrl 메서드 추가
2. updateDiscordWebhook에서 validateDiscordWebhookUrl 호출하여 유효성 검사
=> feat: 디스코드 웹훅 url 유효성 검사 로직 추가

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: eb 데스트

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: rate limit 적용

src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitFilter.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: rate limit 적용-2

src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitFilter.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: rate limit 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitFilter.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitProperties.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: rate limit 테스트-2

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: 데이터베이스 수정사항 반영

src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitFilter.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: rate limit 통합 버킷 사용

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/controller/UpbitSseController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/UpbitSseService.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: 실시간 체결 내역 안보이는 현상 해결

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/UpbitSseService.java
대시 보드 화면에서 웹 소켓 끊어짐 현상을 방지하고자 재 연결 로직을 추가하였습니다.
1. 웹 소켓 끊어짐 현상을 방지하고자 재 연결 로직을 추가
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: 웹 소켓 재 연결 로직 추가

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/controller/CoinController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/controller/response/CoinWithPriceDTO.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/repository/CoinRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/repository/CoinRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/service/CoinService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/service/CoinServiceImpl.java
현재가를 포함한 코인 검색 기능 수정
1. 현재가를 포함한 코인 검색 엔드포인트에 상대 통화를 입력받도록 파라미터 추가
2. JPA 네이밍 메서드에서 QueryDSL로 변경
1. 포스트맨을 사용해서 데이터가 정상적으로 도착하는 것을 확인했습니다.
2. [테스트 2]
3. [테스트 3]
=> 현재가를 포함한 코인 검색 기능 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitFilter.java
rate limit 설정에서 식별 키에 user agent, session id 추가하여 테스트 예정
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: rate limit에 user agent, session id 추가

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: hikari connection 에러 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitFilter.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/config/RateLimitProperties.java
기존에 사용자 IP를 통한 rate-limit제약을 거는것을 동일한 IP로 접속시 같이 rate-limit이 걸리는 문제가 발생하여 쿠키 발급을 통한 rate-limit을 관리하도록 변경하였음
=> fix: rete-limit 로직 변경

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/global/api/AppHttpStatus.java
- 닉네임 2자~10자로 제한하였슴다
1. validateNickname 에서 2~10자 로 제한
=> fix: 닉네임 유효성 검사 로직 추가

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test : github secret 반영

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java
사용자의 닉네임 또는 디스코드 웹훅 정보를 수정할 때, 해당 정보가 실시간 알림(alertSSEService)에도 반영되도록 동기화 로직을 추가
Close #175 
1. updateUserInfo() 내 닉네임 수정 시 alertSSEService.updateUserNicknameInAlerts() 호출 추가
2. updateWebhook() 내 웹훅 수정 시 alertSSEService.updateUserWebhookInAlerts() 호출 추가
=> feat: 닉네임 및 디스코드 웹훅 수정 시 알림 정보 동기화

.github/workflows/deploy-dev-eb.yml
=> test: 배포 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java
디스코드 연동 해제 시에 updateUserWebhookInAlerts 메서드 호출하도록 변경하였습니다.
- Close #175
=> fix: 디스코드 연동 해제 시에 updateUserWebhookInAlerts 메서드 호출하도록 변경

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java
코인 SSE 알람이 가지 않는 버그가 발생하여
로그를 추가하였음
=> chore: 코인 알람 로그 추가

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertSSEService.java
- dev 테스트를 위한 커밋, 
- getter 제거
=> fix: 알람 정보 관련 수정 > getter 제거

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: sse 알림 테스트

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: 운영 환경 배포 테스트-2

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: 운영 환경 배포 테스트-3

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: 운영 환경 배포 테스트-4

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: 운영 환경 배포 테스트-5

.github/workflows/deploy-dev-eb.yml
=> fix: 중복 배포 방지를 위해 버전명을 날짜 기반으로 변경

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> test: 운영 환경 배포 테스트-6

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: timezone 정의

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/repository/jpa/CoinJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/KimchiPremiumServiceImpl.java
- 기존의 특정 세개의 코인만을 조회하여 계산 하던것을 코인테이블에 있는 모든 코인을 연산하도록 수정하였음
=> feat: 김치 프리미엄 모든 데이터 조회 후 연산

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertHistoryRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertHistoryRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertService.java
알림 삭제 시도 시 삭제 되지 않는 오류 수정
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
알림 히스토리 삭제 후, 알림 엔티티를 삭제해야 합니다.
=> hotfix: 알림 삭제 오류 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertHistoryRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertHistoryRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/GoldenCrossJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/TargetPriceJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/VolumeSpikeJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/AuthService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/AuthServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java
- 회원 탈퇴에 대한 기능적인 오류를 개선하고, 로직의 논리적 세션을 분리하여 sop원칙을 적용하였습니다.
1. 사용자 삭제 메서드를 기능별 작은 메서드로 분리하여 가독성 향상
2. 알림 삭제 로직을 최적화하여 벌크 삭제 연산 적용
3. 외래 키 제약조건을 고려한 삭제 순서 정립
4. 코드 유지보수성 및 테스트 용이성 개선
회원 탈퇴 로직에서, removeAuthCookies, processUserData, deleteUserAlertData 함수는 별도의 utiil이나 interface로 주입 받는 것을 제안 드립니다. 로직을 너무 많이 수정하면 오히려 코드 이해에 어려움이 있을 것 같아 따로 분리는 하지 않았습니다.
=> Refactor: 사용자 삭제 로직 개선 및 구조화

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertHistoryRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertHistoryRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/GoldenCrossJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/TargetPriceJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/VolumeSpikeJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/AlertService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/AuthService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/AuthServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/user/service/UserServiceImpl.java
1. 사용자 삭제 메서드를 기능별 작은 메서드로 분리하여 가독성 향상
2. 알림 삭제 로직을 최적화하여 벌크 삭제 연산 적용
3. 외래 키 제약조건을 고려한 삭제 순서 정립
4. 코드 유지보수성 및 테스트 용이성 개선
회원 탈퇴에서 processUserData, removeAuthCookies, deleteUserAlertData 함수의 경우 별도의 util이나 interface로부터 주입 받아 사용하는 것을 제안드립니다.
=> Refactor: 사용자 삭제 로직 개선 및 구조화 

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/service/DiscordService.java
- 로그 메세지 변경
- 실패 시 예외 처리 추가
1. 로그 메세지 변경
2. 실패 시 예외 처리 추가
=> refactor: 디스코드 관련 수정

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Test: cors 에러 수정 테스트

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/KimchiPremiumRepositoryImpl.java
- 서브쿼리를 사용한 날짜 비교 방식에서 2단계 쿼리 방식으로 변경하여 성능 향상
- 코인별 최신 프리미엄 ID를 먼저 조회하고 해당 ID 목록으로 데이터 필터링
- 상관 서브쿼리 제거로 인덱스 활용도 개선 및 쿼리 실행 시간 단축
- 기본 키(id) 기반 조회로 데이터베이스 엔진의 효율적인 검색 활용
1. KimchiPremiumRepositoryImpl의 findAllKimchiPremiums() 메소드 쿼리 최적화
2. 상관 서브쿼리(Correlated Subquery) 제거 및 2단계 쿼리 방식으로 변경
3. 기본 키(id) 인덱스를 효율적으로 활용하는 WHERE 조건으로 변경
=> refactor: KimchiPremium 조회 쿼리 최적화

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/KimchiPremiumRepositoryImpl.java
- 김치 프리미엄의 가격의 내림 차순 -> 코인 id의 오름차순으로 변경
=> refactor: 김치프리미엄 정렬순 변경

.github/workflows/deploy-dev-eb.yml, .github/workflows/deploy-prd-eb.yml, Dockerfile, docker-compose.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Build: yml 수정

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/CandleRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/CandleRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/entity/CandleCompositeKey.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/entity/CandleEntity.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/repository/jpa/CandleJpaRepository.java
- CandelEntity 및 복합키 클래스 구조 생성
- CandleJpaRepository, CandleRepository, Impl 생성
- RSI 및 MACD 계산을 위한 1분봉 캔들 데이터 구조 준비
=> feat: 캔들 기반 지표 계산을 위한 엔티티 및 레포지토리 추가

.github/workflows/deploy-prd-eb.yml, k8s/deployment.yaml
Chore: 운영 환경 자동화 배포 파이프라인 테스트 코드 작성입니다.
1. 쿠버네티스 환경의 자동화 배포 파이프라인 스크립트를 작성했습니다
2. k8s/deployment.yml 파일의 참조 이미지 부분을 수정했습니다.
1. 정상적으로 자동 배포가 이루어지는 지 테스트 해봅니다.
=> Chore: 운영 환경 자동화 배포 파이프라인 테스트

.github/workflows/deploy-prd-eb.yml, k8s/deployment.yaml
운영 환경 자동화 배포 파이프라인 테스트 
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Chore: 운영 환경 자동화 배포 파이프라인 테스트 -2

Dockerfile, k8s/deployment.yaml
운영 환경 자동화 배포 파이프라인 테스트 
1. Dockerfile 에 time zone 추가
2. deployment.yaml에 args 값 추가
=> Chore: 운영 환경 자동화 배포 파이프라인 테스트 -3

.github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Chore: 운영 환경 자동화 배포 파이프라인 구축

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertHistoryRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/AlertSSEJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/GoldenCrossJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/TargetPriceJpaRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/jpa/VolumeSpikeJpaRepository.java
- 똥커밋 날리긴 싫어서 진행하는 사용하지 않는 코드 제거
=> refactor: 사용하지 않는 코드 제거

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepositoryImpl.java
- 티커 데이터 조회 시 상관쿼리 최적화
- 티커 데이터 조회 시 상관쿼리 최적화
=> fix: 티커 데이터 조회 시 상관쿼리 최적화

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/auth/service/JwtBlacklistService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/auth/service/JwtBlacklistServiceImpl.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Fix: JWT 블랙리스트 관련 스케줄러 주석

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/CoinIndicatorServiceImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/dashboard/service/KimchiPremiumServiceImpl.java
- 불필요한 코드(주석) 삭제
- 코인지표에서 데이터 예외처리시 && 되어있던 것을 || 로 수정
=> fix: 예외처리 수정

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Hotfix: jvm 옵션 추가

src/main/java/_1danhebojo/coalarm/coalarm_service/domain/alert/repository/AlertRepositoryImpl.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Hotfix: findLatestTickersBySymbolList 메서드 수정

.github/workflows/deploy-dev-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Hotfix: deploy.yml 수정

.github/workflows/deploy-dev-eb.yml, .github/workflows/deploy-prd-eb.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Hotfix: cicd 파이프라인 점검

build.gradle, k8s/deployment.yaml, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/controller/CoinController.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/controller/response/CoinPredictDTO.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/repository/CoinRepository.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/repository/CoinRepositoryImpl.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/service/CoinService.java, src/main/java/_1danhebojo/coalarm/coalarm_service/domain/coin/service/CoinServiceImpl.java
코인 예측 + 기영이 차트 유사도 관련 api 구현
1. /api/v1/coins/predict?coin=에이브&days=17 경로로 요청
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> feat: 코인 예측 api 구현

CHANGELOG.md, package-lock.json
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Develop -> main 병합 (fastapi 엔드포인트 변경)
